/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-10-09 01:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/NINO/Documents/LapTrinhWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LTW/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/NINO/Documents/LapTrinhWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LTW/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1727802993435L));
    _jspx_dependants.put("jar:file:/C:/Users/NINO/Documents/LapTrinhWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LTW/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN CONTENT -->\r\n");
      out.write("          <div class=\"col-md-9 col-sm-9\">\r\n");
      out.write("          \r\n");
      out.write("            <h1>Create an account</h1>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"content-form-page\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-7 col-sm-7\">\r\n");
      out.write("                  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" method=\"post\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                      <legend>Your personal details</legend>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"firstname\" class=\"col-lg-4 control-label\">First Name <span class=\"require\">*</span></label>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"firstname\" name=\"firstname\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"lastname\" class=\"col-lg-4 control-label\">Last Name <span class=\"require\">*</span></label>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"lastname\" name=\"lastname\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\" class=\"col-lg-4 control-label\">Username <span class=\"require\">*</span></label>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                      <legend>Your password</legend>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\" class=\"col-lg-4 control-label\">Password <span class=\"require\">*</span></label>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"password\" name=\"password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"confirm-password\" class=\"col-lg-4 control-label\">Confirm password <span class=\"require\">*</span></label>\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"confirm-password\" name=\"confirm-password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                      <legend>Newsletter</legend>\r\n");
      out.write("                      <div class=\"checkbox form-group\">\r\n");
      out.write("                        <label>\r\n");
      out.write("                          <div class=\"col-lg-12 col-sm-12\"> Singup for Newsletter \r\n");
      out.write("                          <div class=\"col-lg-4 col-sm-4\">\r\n");
      out.write("                            <input type=\"checkbox\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          \r\n");
      out.write("                        </label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-lg-8 col-md-offset-4 padding-left-0 padding-top-20\">                        \r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Create an account</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\">Cancel</button>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 col-sm-4 pull-right\">\r\n");
      out.write("                  <div class=\"form-info\">\r\n");
      out.write("                    <h2><em>Important</em> Information</h2>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    <p>Duis autem vel eum iriure at dolor vulputate velit esse vel molestie at dolore.</p>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default\">More details</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END CONTENT -->\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
